services:
  - type: web
    name: tadka-play-1
    runtime: node
    rootDir: .
    buildCommand: npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://tadka-play-9x13.vercel.app
      - key: SERVE_CLIENT
        value: false
      - key: PORT
        value: 10000
